{"stop": 1610460368805, "children": ["b797a0a5-a428-466a-a4c1-caab56dc979b", "dba650c8-bbc1-4879-99be-17945c818167"], "start": 1610460349633, "uuid": "f865531e-ac0a-4a82-9571-ba76bf57910b", "befores": [{"statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .//span[contains(text(),'管理员1')]\n\n", "trace": "  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 1124, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\fixtures.py\", line 921, in call_fixture_func\n    fixture_result = next(generator)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 799, in xunit_setup_class_fixture\n    _call_with_optional_argument(func, self.obj)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\_pytest\\python.py\", line 732, in _call_with_optional_argument\n    func(arg)\n  File \"D:\\auto_test\\Autotest_Demo\\Test\\Test_ ManagementCenter\\test_department_manage.py\", line 19, in setup_class\n    self.loginpage.login_in('admin', '20202020', '', '管理员1')\n  File \"D:\\auto_test\\Autotest_Demo\\page\\login_page.py\", line 33, in login_in\n    if self.find_ele(([By.XPATH, \".//span[contains(text(),'{}')]\".format(accoutName)])):\n  File \"D:\\auto_test\\Autotest_Demo\\base\\base_page.py\", line 22, in find_ele\n    self.driver.find_element(loc[0], loc[1])\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 978, in find_element\n    'value': value})['value']\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"d:\\work\\tools3\\python\\python35\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "name": "_Class__pytest_setup_class", "start": 1610460349633, "status": "broken", "stop": 1610460368641}]}